Repository apple/swift-nio-http2, pull requests merged in 2020-08, with the labels that each got.

#224 Add test utilities for `FramePayload`s
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
  Tests/NIOHTTP2Tests/TestUtilities.swift
Labels: needs-no-version-bump

#221 Allow payload-based stream channels to be created.
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
Labels: 🔼 needs-minor-version-bump

#227 Deprecate the HTTP2 to HTTP1 codecs
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
  Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
Labels: 🔼 needs-minor-version-bump

#228 Verify payload-based stream channel fixes #214
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests+XCTest.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
  Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Labels: patch-version-bump-only

#229 Fix the -f option in build_podspec.sh.
  scripts/build_podspec.sh
Labels: needs-no-version-bump

#231 Propagate read() through the pipeline.
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
Labels: patch-version-bump-only

#232 Bring HPACKHeaders function parity closer to HTTPHeaders
  Sources/NIOHPACK/HPACKHeader.swift
  Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
  Tests/NIOHPACKTests/HPACKCodingTests.swift
Labels: 🔼 needs-minor-version-bump

#233 Avoid emitting WINDOW_UPDATE frames when receiving stream closed
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Sources/NIOHTTP2/InboundWindowManager.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/InboundWindowManagerTests+XCTest.swift
  Tests/NIOHTTP2Tests/InboundWindowManagerTests.swift
Labels: patch-version-bump-only

#234 Remove needless branch, clean up variable names.
  Sources/NIOHPACK/IntegerCoding.swift
Labels: patch-version-bump-only
