Repository apple/swift-nio-http2, pull requests merged in 2020-11, with the labels that each got.

#256 Add benchmarks and improve benchmarking.
  .gitignore
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_1k_requests.swift
  Package.swift
  Sources/NIOHTTP2PerformanceTester/ServerOnly10KRequestsBenchmark.swift
  Sources/NIOHTTP2PerformanceTester/main.swift
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.53.yaml
Labels: needs-no-version-bump

#257 Reduce allocations in OutboundFlowControlBuffer.
  Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.53.yaml
Labels: patch-version-bump-only

#258 Implement StreamMap and replace Dictionary
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/Optional+HTTP2StreamStateMachine.swift
  Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
  Sources/NIOHTTP2/StreamMap.swift
  Sources/NIOHTTP2/StreamStateMachine.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP2Tests/StreamMapTests+XCTest.swift
  Tests/NIOHTTP2Tests/StreamMapTests.swift
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.53.yaml
Labels: patch-version-bump-only

#259 Add properties to HTTP2StreamID to determine stream initiator
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
  Sources/NIOHTTP2/HTTP2StreamID.swift
  Tests/NIOHTTP2Tests/StreamIDTests+XCTest.swift
  Tests/NIOHTTP2Tests/StreamIDTests.swift
Labels: 🔼 needs-minor-version-bump

#260 Add benchmark and alloc test for GOAWAY teardown.
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_stream_teardown_100_concurrent.swift
  Sources/NIOHTTP2PerformanceTester/StreamTeardownBenchmark.swift
  Sources/NIOHTTP2PerformanceTester/main.swift
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.53.yaml
Labels: needs-no-version-bump

#262 Move the huffman benchmark base64 out of init
  Sources/NIOHTTP2PerformanceTester/Benchmark.swift
  Sources/NIOHTTP2PerformanceTester/HuffmanDecodingBenchmark.swift
  Sources/NIOHTTP2PerformanceTester/main.swift
Labels: needs-no-version-bump

#261 Improve bulk stream teardown.
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
  Sources/NIOHTTP2/StreamMap.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP2Tests/CircularBufferExtensionsTests+XCTest.swift
  Tests/NIOHTTP2Tests/CircularBufferExtensionsTests.swift
  Tests/NIOHTTP2Tests/StreamMapTests+XCTest.swift
  Tests/NIOHTTP2Tests/StreamMapTests.swift
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.53.yaml
Labels: patch-version-bump-only

#263 Use proper String unsafeUninitializedCapacity initializer.
  Sources/NIOHPACK/HuffmanCoding.swift
  docker/docker-compose.1804.53.yaml
Labels: patch-version-bump-only

#264 Cheaper calculation of flushes.
  Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
Labels: enhancement, patch-version-bump-only
