Repository apple/swift-nio-http2, pull requests merged in 2020-07, with the labels that each got.

#211 Don't install Jazzy on Xenial
  docker/Dockerfile
Labels: needs-no-version-bump

#216 Add HTTP2FrameConvertible and HTTP2FramePayloadConvertible
  Sources/NIOHTTP2/HTTP2Frame.swift
  Sources/NIOHTTP2/HTTP2FrameConvertible.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP2Tests/HTTP2FrameConvertibleTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FrameConvertibleTests.swift
Labels: patch-version-bump-only

#215 Define abstraction for multiplexer holding channel.
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
  Sources/NIOHTTP2/StreamChannelList.swift
Labels: patch-version-bump-only

#217 Update HTTP2StreamChannel to tolerate nil stream ID.
  Sources/NIOHTTP2/HTTP2Error.swift
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
Labels: patch-version-bump-only

#219 Refactor the codecs for extension.
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
Labels: patch-version-bump-only

#218 Make HTTP2StreamChannel generic over a message type
  Sources/NIOHTTP2/HTTP2Frame.swift
  Sources/NIOHTTP2/HTTP2FrameConvertible.swift
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
Labels: patch-version-bump-only

#223 Update the test generation script to allow for deprecated tests
  Tests/LinuxMain.swift
  Tests/NIOHPACKTests/HPACKCodingTests+XCTest.swift
  Tests/NIOHPACKTests/HPACKIntegrationTests+XCTest.swift
  Tests/NIOHPACKTests/HPACKRegressionTests+XCTest.swift
  Tests/NIOHPACKTests/HeaderTableTests+XCTest.swift
  Tests/NIOHPACKTests/HuffmanCodingTests+XCTest.swift
  Tests/NIOHPACKTests/IntegerCodingTests+XCTest.swift
  Tests/NIOHTTP2Tests/CompoundOutboundBufferTest+XCTest.swift
  Tests/NIOHTTP2Tests/ConcurrentStreamBufferTest+XCTest.swift
  Tests/NIOHTTP2Tests/ConfiguringPipelineTests+XCTest.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
  Tests/NIOHTTP2Tests/ControlFrameBufferTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FrameConvertibleTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FrameParserTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests+XCTest.swift
  Tests/NIOHTTP2Tests/InboundWindowManagerTests+XCTest.swift
  Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests+XCTest.swift
  Tests/NIOHTTP2Tests/ReentrancyTests+XCTest.swift
  Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
  Tests/NIOHTTP2Tests/StreamChannelFlowControllerTests+XCTest.swift
  Tests/NIOHTTP2Tests/StreamIDTests+XCTest.swift
  scripts/generate_linux_tests.rb
Labels: needs-no-version-bump

#222 Add HTTP2Frame.FramePayload codecs
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
  Tests/NIOHTTP2Tests/HTTP2StreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/TestUtilities.swift
Labels: 🔼 needs-minor-version-bump
