Repository apple/swift-nio-http2, pull requests merged in 2020-09, with the labels that each got.

#237 Move END_STREAM check earlier.
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
Labels: patch-version-bump-only

#239 Shrink NIOHTTP2WindowUpdatedEvent.
  Sources/NIOHTTP2/HTTP2UserEvents.swift
Labels: patch-version-bump-only

#238 Swift 5.3-RELEASE is here, let's use it
  docker/docker-compose.1804.53.yaml
Labels: needs-no-version-bump

#242 Make HTTP2StreamChannel non-generic
  Sources/NIOHTTP2/HTTP2Frame.swift
  Sources/NIOHTTP2/HTTP2FrameConvertible.swift
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP2Tests/HTTP2FrameConvertibleTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FrameConvertibleTests.swift
  Tests/NIOHTTP2Tests/TestUtilities.swift
Labels: patch-version-bump-only

#243 Remove a few unnecessary allocations.
  Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
Labels: patch-version-bump-only

#246 Reduce allocations when peeking pseudo-headers.
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_h1_request_response.swift
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.53.yaml
Labels: patch-version-bump-only

#248 Use the non-deprecated 'configureHTTP2Pipeline' in benchmarks
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_h1_request_response.swift
Labels: needs-no-version-bump

#249 Update alloc counter scaffolding.
  IntegrationTests/tests_01_allocation_counters/test_01_allocation_counts.sh
  IntegrationTests/tests_01_allocation_counters/test_01_resources/run-nio-http2-alloc-counter-tests.sh
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.53.yaml
  scripts/integration_tests.sh
Labels: needs-no-version-bump

#247 Add a location to each of 'NIOHTTP2Errors'
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingGoAwayState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingPushPromiseState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingGoawayState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingPushPromiseState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/HTTP2SettingsState.swift
  Sources/NIOHTTP2/ContentLengthVerifier.swift
  Sources/NIOHTTP2/DOSHeuristics.swift
  Sources/NIOHTTP2/Frame Buffers/ConcurrentStreamBuffer.swift
  Sources/NIOHTTP2/Frame Buffers/ControlFrameBuffer.swift
  Sources/NIOHTTP2/Frame Buffers/OutboundFlowControlBuffer.swift
  Sources/NIOHTTP2/HPACKHeaders+Validation.swift
  Sources/NIOHTTP2/HTTP2ChannelHandler.swift
  Sources/NIOHTTP2/HTTP2Error.swift
  Sources/NIOHTTP2/HTTP2FlowControlWindow.swift
  Sources/NIOHTTP2/HTTP2FrameParser.swift
  Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
  Sources/NIOHTTP2/StreamStateMachine.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP2Tests/CompoundOutboundBufferTest.swift
  Tests/NIOHTTP2Tests/ConcurrentStreamBufferTest.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
  Tests/NIOHTTP2Tests/ControlFrameBufferTests.swift
  Tests/NIOHTTP2Tests/HTTP2ErrorTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2ErrorTests.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
  Tests/NIOHTTP2Tests/OutboundFlowControlBufferTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Labels: 🔼 needs-minor-version-bump

#250 We now use the main branch.
  README.md
  docker/Dockerfile
  scripts/check_no_api_breakages.sh
  scripts/generate_linux_tests.rb
Labels: needs-no-version-bump
