Repository apple/swift-nio-http2, pull requests merged in 2021-06, with the labels that each got.

#290 Update our allocation counter numbers.
  dev/alloc-limits-from-test-output
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.2004.55.yaml
Labels: needs-no-version-bump

#289 stop publishing the executable products
  Package.swift
Labels: needs-no-version-bump

#292 Remove support for Swift 5.0 and 5.1
  Package.swift
  README.md
  docker/Dockerfile
  docker/docker-compose.1604.51.yaml
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1804.50.yaml
  scripts/check_no_api_breakages.sh
Labels: 🔼 needs-minor-version-bump

#293 Update NIO dependency to 2.30.0
  Package.swift
Labels: patch-version-bump-only
