Repository apple/swift-nio-http2, pull requests merged in 2021-11, with the labels that each got.

#311 Remove forbidden HTTP1 headers even if no connection header is present
  Sources/NIOHPACK/HPACKHeader.swift
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
Labels: patch-version-bump-only

#314 Swift nightly has improved alloc counts.
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#315 Deliver outbound stream errors to channels.
  Sources/NIOHTTP2/HTTP2ChannelHandler.swift
  Sources/NIOHTTP2/HTTP2Error.swift
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  Sources/NIOHTTP2/MultiplexerAbstractChannel.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests+XCTest.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Labels: 🔼 needs-minor-version-bump

#316 Add Transfer-Encoding chunked to HTTP1 requests and responses.
  Sources/NIOHTTP2/HTTP2ToHTTP1Codec.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadToHTTP1CodecTests.swift
  Tests/NIOHTTP2Tests/HTTP2ToHTTP1CodecTests.swift
Labels: patch-version-bump-only

#317 Forward all reads before stream channel inactive
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests+XCTest.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
Labels: patch-version-bump-only
