Repository apple/swift-nio-http2, pull requests merged in 2022-05, with the labels that each got.

#340 Add script to list transitive dependencies
  scripts/build_podspec.sh
  scripts/list_transitive_dependencies.py
Labels: needs-no-version-bump

#341 Remove build_podspec.sh
  scripts/build_podspec.sh
  scripts/list_topsorted_dependencies.sh
  scripts/list_transitive_dependencies.py
Labels: needs-no-version-bump

#344 Make HPACKHeaders hashable.
  Sources/NIOHPACK/HPACKHeader.swift
  Tests/LinuxMain.swift
  Tests/NIOHPACKTests/HPACKHeadersTests+XCTest.swift
  Tests/NIOHPACKTests/HPACKHeadersTests.swift
Labels: 🔼 needs-minor-version-bump

#346 HPACKHeaders performance test for HTTPHeader normalisation
  Sources/NIOHTTP2PerformanceTester/HPACKHeadersNormalizationOfHTTPHeadersBenchmark.swift
  Sources/NIOHTTP2PerformanceTester/main.swift
Labels: needs-no-version-bump

#347 Improve HTTPHeader normalisation performance for large inputs
  Sources/NIOHPACK/HPACKHeader.swift
  Tests/NIOHPACKTests/HPACKHeadersTests+XCTest.swift
  Tests/NIOHPACKTests/HPACKHeadersTests.swift
Labels: patch-version-bump-only
