Repository apple/swift-nio-http2, pull requests merged in 2022-02, with the labels that each got.

#325 Make UnrepresentableInteger public
  Sources/NIOHPACK/HPACKErrors.swift
Labels: 🔼 needs-minor-version-bump

#326 Update minimum dependency version in README
  README.md
Labels: needs-no-version-bump

#327 Remove a retain/release
  Sources/NIOHPACK/HPACKDecoder.swift
Labels: patch-version-bump-only

#328 Use unchecked math in encodeInteger
  Sources/NIOHPACK/IntegerCoding.swift
Labels: patch-version-bump-only
