Repository apple/swift-nio-http2, pull requests merged in 2023-10, with the labels that each got.

#422 DOSHeuristics DeadlineClock more explicit on 5.6
  Sources/NIOHTTP2/DOSHeuristics.swift
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: patch-version-bump-only

#420 Bump minimum Swift version to 5.7
  Package.swift
  README.md
  Sources/NIOHTTP2/DOSHeuristics.swift
  Sources/NIOHTTP2/HTTP2ChannelHandler.swift
  Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.59.yaml
Labels: 🔼 needs-minor-version-bump

#425 Remove retroactive `CustomDebugStringConvertible` conformance in tests
  Tests/NIOHPACKTests/HPACKIntegrationTests.swift
Labels: needs-no-version-bump
