Repository apple/swift-nio-http2, pull requests merged in 2023-02, with the labels that each got.

#370 Update allocation limits
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.main.yaml
Labels: needs-no-version-bump

#369 ContentLengthVerifier Update
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStreamsState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingPushPromiseState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingPushPromiseState.swift
  Sources/NIOHTTP2/ContentLengthVerifier.swift
  Sources/NIOHTTP2/StreamStateMachine.swift
  Sources/NIOHTTP2Server/main.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
  Tests/NIOHTTP2Tests/ContentLengthVerifierTests+XCTest.swift
  Tests/NIOHTTP2Tests/ContentLengthVerifierTests.swift
Labels: patch-version-bump-only

#371 Content-Length errors shouldn't crash
  Sources/NIOHTTP2/HTTP2Error.swift
  Sources/NIOHTTP2/StreamStateMachine.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests+XCTest.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Labels: patch-version-bump-only

#372 Better handle writes issued with already completed promises
  Sources/NIOHTTP2/WatermarkedFlowController.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests+XCTest.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
Labels: patch-version-bump-only

#373 Ensure that we fire channelActive and channelInactive in order
  Sources/NIOHTTP2/HTTP2ChannelHandler.swift
  Sources/NIOHTTP2/HTTP2Error.swift
  Tests/NIOHTTP2Tests/HTTP2FramePayloadStreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/ReentrancyTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
  Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Labels: 🔼 needs-minor-version-bump

#374 Correctly respect changes to HEADER_TABLE_SIZE
  Sources/NIOHPACK/HPACKEncoder.swift
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
  Sources/NIOHTTP2/ConnectionStateMachine/HasLocalSettings.swift
  Sources/NIOHTTP2/ConnectionStateMachine/HasRemoteSettings.swift
  Tests/NIOHPACKTests/HPACKCodingTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerTests+XCTest.swift
  Tests/NIOHTTP2Tests/SimpleClientServerTests.swift
Labels: patch-version-bump-only
