Repository apple/swift-nio-http2, pull requests merged in 2024-06, with the labels that each got.

#442 Update soundness, it is 2024 now
  scripts/soundness.sh
Labels: needs-no-version-bump

#441 Implement RFC8441 Extended CONNECT
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingHeadersState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameSendingStates/SendingHeadersState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/HTTP2SettingsState.swift
  Sources/NIOHTTP2/ConnectionStateMachine/HasExtendedConnectSettings.swift
  Sources/NIOHTTP2/ConnectionStateMachine/HasLocalSettings.swift
  Sources/NIOHTTP2/ConnectionStateMachine/HasRemoteSettings.swift
  Sources/NIOHTTP2/HPACKHeaders+Validation.swift
  Sources/NIOHTTP2/HTTP2ConnectionStateChange.swift
  Sources/NIOHTTP2/HTTP2Error.swift
  Sources/NIOHTTP2/StreamStateMachine.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
  Tests/NIOHTTP2Tests/HTTP2ErrorTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
  Tests/NIOHTTP2Tests/TestUtilities.swift
Labels: 🔼 needs-minor-version-bump

#444 Discard read bytes when accumulating continuation frames
  Sources/NIOHTTP2/HTTP2FrameParser.swift
Labels: patch-version-bump-only
