Repository apple/swift-nio-http2, pull requests merged in 2024-07, with the labels that each got.

#443 Reject long sequences of CONTINUATION frames
  Sources/NIOHTTP2/HTTP2ChannelHandler.swift
  Sources/NIOHTTP2/HTTP2Error.swift
  Sources/NIOHTTP2/HTTP2FrameParser.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
  Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
  Tests/NIOHTTP2Tests/HTTP2InlineStreamMultiplexerTests.swift
  Tests/NIOHTTP2Tests/SimpleClientServerFramePayloadStreamTests.swift
  Tests/NIOHTTP2Tests/TestUtilities.swift
Labels: patch-version-bump-only

#446 Reduce error allocations
  Sources/NIOHTTP2/Error+Any.swift
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
Labels: patch-version-bump-only

#447 Keep capacity when dropping pending reads in the stream channel
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
Labels: patch-version-bump-only

#448 Use Bionic module from new Android overlay in Swift 6 instead
  Tests/NIOHTTP2Tests/TestUtilities.swift
Labels: needs-no-version-bump

#451 Add alloc tests for alternative stream creation API
  IntegrationTests/tests_01_allocation_counters/test_01_resources/shared.swift
  IntegrationTests/tests_01_allocation_counters/test_01_resources/test_create_client_stream_channel.swift
  Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#450 Reduce allocations on `InlineStreamMultiplexer/createStreamChannel`
  Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: patch-version-bump-only

#428 Make HEADERS frame payload non-indirect
  Sources/NIOHTTP2/HTTP2Frame.swift
  Tests/NIOHTTP2Tests/HTTP2FrameParserTests.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#449 Reduce allocs in HTTP2StreamChannel
  Sources/NIOHTTP2/HTTP2StreamChannel.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: patch-version-bump-only

#445 Fix bug where client ignores HEADERS frames on open stream when locally quiescing
  Sources/NIOHTTP2/ConnectionStateMachine/ConnectionStateMachine.swift
  Sources/NIOHTTP2/ConnectionStateMachine/FrameReceivingStates/ReceivingHeadersState.swift
  Tests/NIOHTTP2Tests/ConnectionStateMachineTests.swift
Labels: patch-version-bump-only

#454 Update allocation limits
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
Labels: needs-no-version-bump

#452 Adopt `release.yml`
  .github/release.yml
Labels: needs-no-version-bump
