Repository apple/swift-nio-http2, pull requests merged in 2024-11, with the labels that each got.

#471 Add a variant of `configureAsyncHTTPServerPipeline` which takes a stream delegate
  Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
  Tests/NIOHTTP2Tests/ConfiguringPipelineAsyncMultiplexerTests.swift
Labels: semver/minor

#480 Make configureHTTP2AsyncSecureUpgrade public
  Sources/NIOHTTP2/HTTP2PipelineHelpers.swift
Labels: semver/minor

#482 unify scheduled and main yamls
  .github/workflows/main.yml
  .github/workflows/scheduled.yml
Labels: semver/none

#483 Finish multiplexer's inbound streams in more cases
  Sources/NIOHTTP2/HTTP2ChannelHandler+InboundStreamMultiplexer.swift
  Sources/NIOHTTP2/HTTP2ChannelHandler+InlineStreamMultiplexer.swift
  Sources/NIOHTTP2/HTTP2ChannelHandler.swift
  Sources/NIOHTTP2/HTTP2CommonInboundStreamMultiplexer.swift
  Tests/NIOHTTP2Tests/SimpleClientServerInlineStreamMultiplexerTests.swift
Labels: semver/patch

#485 Aligning semantic version label check name
  .github/workflows/pull_request_label.yml
Labels: semver/none
